name: Push Docker Images

on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types:
      - completed
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  prepare:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set matrix
        id: set-matrix
        run: |
          MATRIX=$(cat .github/docker-images.json | jq -c '{include: .images}')
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  push-to-dockerhub:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.name }}_${{ matrix.tag }}
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/${{ matrix.name }}_${{ matrix.tag }}.tar
          docker tag ${{ matrix.name }}:${{ matrix.tag }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.name }}:${{ matrix.tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.name }}:${{ matrix.tag }}

  push-to-aliyun:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.name }}_${{ matrix.tag }}
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/${{ matrix.name }}_${{ matrix.tag }}.tar
          docker tag ${{ matrix.name }}:${{ matrix.tag }} registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACE }}/${{ matrix.name }}:${{ matrix.tag }}

      - name: Login to Aliyun Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Push to Aliyun
        run: docker push registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACE }}/${{ matrix.name }}:${{ matrix.tag }} 